[package]
name = "fluent"
version = "0.1.0"
authors = ["Camille TJHOA <camille@contract-live.com>"]

[dependencies]
regex = "0.2"
lazy_static = "^0.2"

[dependencies.nom]
version = "^3.2"
features = ["regexp", "regexp_macros", "verbose-errors"]
